#!/usr/bin/env python3
"""Restore missing repo files to GitHub main via git-database API.

Root cause of failed Vercel builds: src/ on GitHub main only had 7 blobs,
so `npm run build` failed at prebuild with `Cannot find module '../src/lib/search'`.
This script pushes every local repo file that is absent from GitHub main.
Local-only (not committed).
"""
import base64, hashlib, json, os, sys, urllib.request

sys.path.insert(0, "/home/hatch/workspace/skills/github/bin")
from gh_publish import api_request

ROOT = os.path.expanduser("~/workspace/student-learning-website")
OWNER, REPO = "aliaaquib", "student-learning-website"

SKIP_DIRS = {".next", "out", "node_modules", "__pycache__", ".git"}
SKIP_FILES = {"LESSON_REVIEW_REPORT.md"}
SKIP_SUFFIXES = (".py", ".tsbuildinfo", ".log")
SKIP_PATHS = {"public/search-index.json"}  # generated by prebuild

def blob_sha(path):
    with open(path, "rb") as f:
        raw = f.read()
    return hashlib.sha1(b"blob %d\0" % len(raw) + raw).hexdigest()

# current github blobs
with urllib.request.urlopen(
    f"https://api.github.com/repos/{OWNER}/{REPO}/git/trees/main?recursive=1",
    timeout=60,
) as r:
    tree_data = json.loads(r.read())
gh_blobs = {x["path"] for x in tree_data["tree"] if x["type"] == "blob"}
print(f"github blobs: {len(gh_blobs)}")

# local candidate files
local_files = []
for root, dirs, files in os.walk(ROOT):
    dirs[:] = [d for d in dirs if d not in SKIP_DIRS]
    for f in files:
        rel = os.path.relpath(os.path.join(root, f), ROOT)
        if f in SKIP_FILES or rel in SKIP_PATHS or f.endswith(SKIP_SUFFIXES):
            continue
        if rel.startswith("."):
            continue
        local_files.append(rel)

missing = sorted(set(local_files) - gh_blobs)
print(f"local files: {len(local_files)}, missing from github: {len(missing)}")
for m in missing:
    print("  +", m)

if not missing:
    print("nothing to push")
    sys.exit(0)

ref = api_request("GET", f"/repos/{OWNER}/{REPO}/git/ref/heads/main")
head_sha = ref["object"]["sha"]
head_commit = api_request("GET", f"/repos/{OWNER}/{REPO}/git/commits/{head_sha}")
base_tree = head_commit["tree"]["sha"]
print("base:", head_sha[:12])

entries = []
for rel in missing:
    full = os.path.join(ROOT, rel)
    sha = blob_sha(full)
    with open(full, "rb") as f:
        content = base64.b64encode(f.read()).decode()
    r = api_request("POST", f"/repos/{OWNER}/{REPO}/git/blobs",
                    {"content": content, "encoding": "base64"})
    assert r["sha"] == sha, f"sha mismatch for {rel}"
    entries.append({"path": rel, "mode": "100644", "type": "blob", "sha": sha})
print(f"uploaded {len(entries)} blobs")

tree = api_request("POST", f"/repos/{OWNER}/{REPO}/git/trees",
                   {"base_tree": base_tree, "tree": entries})
print("tree:", tree["sha"][:12])

commit = api_request("POST", f"/repos/{OWNER}/{REPO}/git/commits", {
    "message": "Restore missing src/ and public/ files dropped by earlier pushes\n\nThe blog/perf pushes left src/ with only 7 files on main, breaking\n`npm run build` at the prebuild step (Cannot find module '../src/lib/search').\nThis restores every repo file present locally but absent from main.",
    "tree": tree["sha"],
    "parents": [head_sha],
})
print("commit:", commit["sha"])

upd = api_request("PATCH", f"/repos/{OWNER}/{REPO}/git/refs/heads/main",
                  {"sha": commit["sha"]})
print("ref updated:", upd["object"]["sha"][:12])
